### ISSUE TITLE
proposal to change the check file location

### ISSUE THREAD

**Issue by edmundlaugasson** [magavdraakon/i-tee#21]
Here would be proposal to change the check file location:
`/tmp/checkfile -> /var/tmp/checkfile`

This will affect those checks that depend on previous step, e.g. SSH login, etc. Once the server has been shut down by script, the check file will be deleted and other depending checks won't work even the check mark is already green. This applies to all learning spaces using vTA.

**Comment by magavdraakon** [comment]
vTA is not a part of i-tee project. This seems that it is a lab content issue. Wontfix.
