### ISSUE TITLE
proposal: router public key in server

### ISSUE THREAD

**Issue by edmundlaugasson** [magavdraakon/i-tee#22]
Sometimes students will delete a router public key from /root/.ssh/authorized_keys file. Here would be a proposal to create the CRON job to ensure the key will be copied back once it is deleted to ensure the router can check the progress in server. This applies to all learning spaces using vTA.

**Comment by tiiatanav** [comment]
Everything to do with files and such in virtual machines is up to the lab creator.

As the lab creator you need to write your services / scripts so, that mission-critical files will be restored if they go missing or corrupt. Sometimes it is best to include a machine (like a lab router) that the student does not have access to and that can govern  over other machines in the lab (setup, grading etc.).

**Comment by magavdraakon** [comment]
This is not i-tee issue. Wontfix
